### ISSUE TITLE
Plugin causes Sketch 48 to shutdown..

### ISSUE THREAD

**Issue by HHSjoelplas** [tarngerine/sketch-name-artboards#14]
MacOS Sierra 10.12.6

**Comment by tarngerine** [comment]
Thanks for the report. Can you grab the crash log? After sketch crashes and
you reopen there's usually a dialog that's like "sketch closed
unexpectedly" with a [see details] button. Click that button and copy paste
that log here? Otherwise I'll check it out later

**Comment by ghost** [comment]
Here you go:

the resolution I'm using is 1x and the Draw slices checkbox is selected.

Incident Identifier: 1D18A09C-B020-461C-B42A-FC92B0898A74
CrashReporter Key:   EE249C1D-81C8-5D1E-8C02-BF28CDA7E4F8
Hardware Model:      MacBookPro11,4
Process:         Sketch [54708]
Path:            /Applications/Sketch.app/Contents/MacOS/Sketch
Identifier:      com.bohemiancoding.sketch3
Version:         48 (47235)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2017-12-06 12:32:59 +0000
OS Version:      Mac OS X 10.12.6 (16G1036)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x7fffbcdd0d42
Crashed Thread:  17

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSColor NSColorForContext:]: unrecognized selector sent to instance 0x618000ebd400'

**Comment by tarngerine** [comment]
Ah thanks. This is due to the change to use MSImmutableColor and sketch
crashes lol now instead of throwing a warning. Will put up a fix soon

**Comment by tarngerine** [comment]
I've published a new release you can download and install over your current version: https://github.com/tarngerine/sketch-name-artboards/releases/tag/v1.7

**Comment by ghost** [comment]
Great, thanks for the fast solution!

<https://www.facebook.com/CMDHHS><https://www.facebook.com/CMDHHS>


On 6 December 2017 at 15:28:47, Julius Tarng (notifications@github.com<mailto:notifications@github.com>) wrote:

Closed #14<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftarngerine%2Fsketch-name-artboards%2Fissues%2F14&data=02%7C01%7CJ.G.S.Plas%40hhs.nl%7C795507abbca24372230608d53cb5a83f%7Ca2586b9bf8674b3c93635b435c5dbc45%7C0%7C0%7C636481673268743803&sdata=epVuBMvPEcskGONm2hsKTafSiV8Eh8bhjx0IZK4ONg8%3D&reserved=0>.
